steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cloud-functions-universal-feedback', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'feedback', '--region', 'us-east1', '--env-vars-file', '.env.yaml']
  dir: 'functions/autodeploy'